export const plans = [
  {
    title: "Stater",
    Duration: "2 weeks",
    price: "$1,000",
    min: "1000",
    roi: "60%",
    offers: [
      "15 daily top up",
      "10000 max price",
      "35% interest",
      "250% compound interest",
      "Hashrate 10ph/s",
      "10% profit bonus",
    ],
  },
  {
    title: "Basic",
    Duration: "2 weeks",
    price: "$1,000",
    min: "1000",
    roi: "60%",
    offers: [
      "20 daily top up",
      "5000 max price",
      "30% interest",
      "50% compound interest",
      "Hashrate 10ph/s",
      "10% profit bonus",
    ],
  },
  {
    title: "Gold",
    Duration: "2 weeks",
    price: "$5,000",
    min: "5000",
    roi: "60%",
    offers: [
      "10 daily top up",
      "20000 max price",
      "20% interest",
      "10% compound interest",
      "Hashrate 10ph/s",
      "10% profit bonus",
    ],
  },
  {
    title: "Sliver",
    Duration: "2 weeks",
    price: "$5,000",
    min: "5000",
    roi: "60%",
    offers: [
      "15 daily top up",
      "10000 max price",
      "35% interest",
      "250% compound interest",
      "Hashrate 10ph/s",
      "15% profit bonus",
    ],
  },
  {
    title: "Standard",
    Duration: "1 month",
    price: "$10,000",
    min: "10000",
    roi: "60%",
    offers: [
      "20 daily top up",
      "10000 max price",
      "10% interest",
      "10% compound interest",
      "Hashrate 10ph/s",
      "10% profit bonus",
    ],
  },
  {
    title: "VIP",
    Duration: "2 Months",
    price: "$50,000",
    min: "50000",
    roi: "60%",
    offers: [
      "20 daily top up",
      "50000 max price",
      "10% interest",
      "10% compound interest",
      "Hashrate 10ph/s",
      "10% profit bonus",
    ],
  },
];
